### ISSUE TITLE
About code issues

### ISSUE THREAD

**Issue by wutongshu819274135** [anita-hu/MSAF#7]
Hello, can the code in Figure 3 in the paper be published? I want to see a section of that code. Thank you

**Comment by anita-hu** [comment]
Hi, you can find the code for emotion recognition in https://github.com/anita-hu/MSAF/tree/master/ravdess. Our model code can be found in https://github.com/anita-hu/MSAF/blob/master/ravdess/networks/msaf_ravdess.py

**Comment by wutongshu819274135** [comment]
thank you very much
